# Generated by Django 5.0.7 on 2024-07-23 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arriendos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='image_url',
            field=models.URLField(null=True),
        ),
    ]
